import { Inter } from "next/font/google";
import "./globals.css";
import LoginBtn from "./LoginBtn.js"
import LogoutBtn from "./LogoutBtn.js"

import {getServerSession} from 'next-auth'
import {authOptions} from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          {
            session ? <span>{session.user.name}<LogoutBtn></LogoutBtn></span>:<LoginBtn></LoginBtn>
          }
        </div> 
        {children}
      </body>
    </html>
  );
}
